# Generated by Django 4.0.3 on 2022-04-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['deleted', 'id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='childrenproduct',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='childrenproduct',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='collection',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Удален?'),
        ),
    ]
