# Generated by Django 4.0.3 on 2022-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_date',
            new_name='issue_date',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Статус заказа'),
        ),
    ]
