# Generated by Django 4.0.3 on 2022-04-08 05:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_create_date_order_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
