# Generated by Django 4.0.3 on 2022-04-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='store.product', verbose_name='Избранные'),
        ),
    ]
