# Generated by Django 4.0.3 on 2022-04-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', related_query_name='customers', to='store.product', verbose_name='Избранные'),
        ),
    ]
