# Generated by Django 4.0.3 on 2022-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_city_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='store.product', verbose_name='Избранные'),
        ),
    ]
