# Generated by Django 4.0.3 on 2022-05-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_customer_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorites',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product', verbose_name='Избранные'),
        ),
    ]
