# Generated by Django 4.0.3 on 2022-05-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_favorites_customer_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Избранные'),
        ),
    ]
