# Generated by Django 4.0.3 on 2022-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorites',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='store.product', verbose_name='Избранные'),
        ),
    ]
