# Generated by Django 4.0.3 on 2022-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_customer_favorites_customer_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='store.product', verbose_name='Избранные'),
        ),
    ]
