# Generated by Django 4.0.3 on 2022-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='header_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер телефона в хедере'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealtype',
            name='name',
            field=models.CharField(choices=[('CallBack', 'Обратный звонок'), ('Order', 'Заказ')], max_length=30, verbose_name='Название обращения'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Mail', 'Почта'), ('Footer phones', 'Номера на футере')], max_length=50, verbose_name='Название'),
        ),
    ]
