# Generated by Django 4.0.3 on 2022-04-12 10:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_site_header_phone_alter_appealtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши преимущества', max_length=50, verbose_name='Заголовок')),
                ('icon', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Иконка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='our_advantages_icon',
        ),
        migrations.RemoveField(
            model_name='site',
            name='our_advantages_text',
        ),
        migrations.RemoveField(
            model_name='site',
            name='our_advantages_title',
        ),
    ]
