# Generated by Django 4.0.3 on 2022-04-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_outadvantages_remove_site_our_advantages_icon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutAdvantages',
            new_name='OurAdvantages',
        ),
        migrations.AlterModelOptions(
            name='ouradvantages',
            options={'verbose_name': 'Наши преимущества', 'verbose_name_plural': 'Наши преимущества'},
        ),
    ]
