# Generated by Django 4.0.3 on 2022-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
