# Generated by Django 4.0.3 on 2022-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Удален?'),
        ),
    ]
