# Generated by Django 4.0.3 on 2022-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_is_active_post_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
