# Generated by Django 4.0.3 on 2022-04-08 08:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
